### ISSUE TITLE
duplicate Initialization

### ISSUE THREAD

**Issue by selfsame** [arcadia-unity/Arcadia#220]
When starting Unity, Arcadia's static `Initialization` fires twice (https://github.com/arcadia-unity/Arcadia/blob/develop/Editor/Initialization.cs#L13)

Note that when starting Unity with recompile worthy changes in Assets, it fires 4x

**Comment by selfsame** [comment]
Closing as this is a Unity issue with `[InitializeOnLoad]` https://issuetracker.unity3d.com/issues/unityeditor-dot-initializeonload-calls-the-constructor-twice-when-the-editor-opens

It's supposedly fixed in 5.5+

**Comment by jeaye** [comment]
I see this issue on `5.5.2xf1` on GNU/Linux. I think all of us are on `5.5+` and we see it. Do you mean something more like `>5.5`, or is this actually not fixed?

**Comment by selfsame** [comment]
The issuetracker says it was fixed in 5.5, but yeah seems it's still going on

**Comment by nasser** [comment]
Oof. We can write some logic that protects against this with an e.g. `Initialization.DidInitialize` static boolean.

**Comment by selfsame** [comment]
tried a static bool but it gets flushed, could possibly look into writing a file to disk but feel like we should just grin and bear it until unity gets it's junk together

**Comment by jeaye** [comment]
> tried a static bool but it gets flushed, could possibly look into writing a file to disk but feel like we should just grin and bear it until unity gets it's junk together

Yeah. What's important, I think, is that we all make it clear, on Unity's tracker, that this issue still exists and is not fixed in 5.5

**Comment by selfsame** [comment]
Going to reopen this as we probably have the most investment in getting it resolved. Next step should be getting the latest unity editor, creating a simple reproduction, and reporting a bug from within the editor.

**Comment by selfsame** [comment]
https://fogbugz.unity3d.com/default.asp?893975_1tm2e700vnpjaf90

**Comment by selfsame** [comment]
They have clarified that this is "by design"
https://fogbugz.unity3d.com/default.asp?893975_1tm2e700vnpjaf90

**Comment by selfsame** [comment]
This issue is fixed in the unreleased beta https://fogbugz.unity3d.com/default.asp?893975_1tm2e700vnpjaf90
